language: ruby
before_install: gem install bundler
rvm:
  - 1.8.7-p374
  - 1.9.2-p330
  - 1.9.3-p551
  - ree-1.8.7-2012.02
  - 2.0.0-p598
  - 2.1.5
  - 2.2.0
gemfile:
  - test/gemfiles/Gemfile.ruby
  - test/gemfiles/Gemfile.rails-2.3.x
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
matrix:
  exclude:
    - rvm: 2.0.0-p598
      gemfile: test/gemfiles/Gemfile.rails-2.3.x
    - rvm: 2.1.5
      gemfile: test/gemfiles/Gemfile.rails-2.3.x
    - rvm: 2.2.0
      gemfile: test/gemfiles/Gemfile.rails-2.3.x
    - rvm: 1.8.7-p374
      gemfile: test/gemfiles/Gemfile.rails-3.0.x
    - rvm: ree-1.8.7-2012.02
      gemfile: test/gemfiles/Gemfile.rails-3.0.x
    - rvm: 1.8.7-p374
      gemfile: test/gemfiles/Gemfile.rails-3.1.x
    - rvm: ree-1.8.7-2012.02
      gemfile: test/gemfiles/Gemfile.rails-3.1.x
    - rvm: 1.9.2-p330
      gemfile: test/gemfiles/Gemfile.rails-3.1.x
    - rvm: 1.8.7-p374
      gemfile: test/gemfiles/Gemfile.rails-3.2.x
    - rvm: ree
      gemfile: test/gemfiles/Gemfile.rails-3.2.x
    - rvm: 1.9.2-p330
      gemfile: test/gemfiles/Gemfile.rails-3.2.x
    - rvm: 1.8.7-p374
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: ree-1.8.7-2012.02
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 1.9.2-p330
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 1.8.7-p374
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: ree
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: 1.9.2-p330
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
